# Generated by Django 5.2.7 on 2025-11-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='idempotency_key',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('BKASH', 'bKash'), ('NAGAD', 'Nagad')], max_length=10),
        ),
    ]
